javascripts:
    core:
        - public/javascripts/vendor/jquery.js
        - public/javascripts/vendor/underscore.js
        - public/javascripts/vendor/backbone.js
        - app/views/common/*.jst
        - public/javascripts/views/**/*.js
        - public/javascripts/models/**/*.js
        - public/javascripts/application.js

template_function: _.template